# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeather', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='calculation',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.Weather'),
        ),
    ]
